# NumPy Day 2 — Code Lab

**Beginner → ML Foundation**

Topics: Aggregation, Axis, Reshape, Flatten, Transpose, Boolean Masking, Array Creation, Random Numbers, Broadcasting, Matrix Operations, and a Mini ML Dataset.

## Part 1 — Aggregation Functions

In [1]:
import numpy as np

marks = np.array([70, 80, 65, 90, 75])

# Task 1: Find the total marks
# Write your code here

print(np.sum(marks))


380


In [2]:
# Task 2: Find the average marks
# Write your code here
print(np.mean(marks))

76.0


In [3]:
# Task 3: Find the minimum and maximum marks
# Write your code here
print(np.min(marks))
print(np.max(marks))

65
90


In [4]:
# Task 4: Find the standard deviation
# Write your code here
print(np.std(marks))

8.602325267042627


## Part 2 — Axis

In [5]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Task 5: Find the sum of each column
# Hint: axis=0
# Write your code here
print(data.shape)
print(np.sum(marks,axis=0))
print(np.sum(marks,axis=1))

(3, 3)
380


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
# Task 6: Find the sum of each row
# Hint: axis=1
# Write your code here
print(np.sum(marks,axis=1))

AxisError: axis 1 is out of bounds for array of dimension 1

## Part 3 — Reshaping

In [ ]:
# Task 7: Convert the 1D array into a 2 x 3 array

arr = np.array([1, 2, 3, 4, 5, 6])

# Write your code here

arr2 = arr.reshape(2,3)
print(arr2)


[[1 2 3]
 [4 5 6]]


In [ ]:
# Task 8: Convert the array into a 3 x 2 array

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Write your code here
arr2 = arr.reshape(3,2)
print(arr2)


[[1 2]
 [3 4]
 [5 6]]


## Part 4 — Flattening

In [ ]:
# Task 9: Convert this 2D array into 1D using flatten()

data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Write your code here
print(data.flatten())


[1 2 3 4 5 6]


## Part 5 — Transpose

In [ ]:
# Task 10: Transpose the array using .T

data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Write your code here

print(data.T)


[[1 4]
 [2 5]
 [3 6]]


## Part 6 — Boolean Masking

In [ ]:
marks = np.array([45, 78, 90, 32, 88, 65])

# Task 11: Print marks greater than 70
# Write your code here
print(marks > 80)

[False False  True False  True False]


In [ ]:
# Task 12: Print marks less than 50
# Write your code here


In [ ]:
# Task 13: Print marks between 50 and 80
# Hint: use (marks >= 50) & (marks <= 80)
# Write your code here
marks[(marks >= 50) & (marks <= 80)]

array([78, 65])

## Part 7 — Array Creation

In [ ]:
# Task 14: Create an array of five zeros
# Write your code here
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# Task 15: Create an array of five ones
# Write your code here
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [ ]:
# Task 16: Create numbers from 1 to 20 using np.arange()
# Write your code here
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Task 17: Create 5 equally spaced numbers between 0 and 1 using np.linspace()
# Write your code here

np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

## Part 8 — Random Numbers

In [ ]:
# Task 18: Generate 10 random integers between 1 and 100
# Write your code here
np.random.randint(1,100,5)

array([33, 65, 29,  3, 55])

In [ ]:
# Task 19: Generate 5 random decimal numbers between 0 and 1
# Write your code here
np.random.rand(5)

array([0.82568385, 0.26902853, 0.23314685, 0.69561064, 0.5493779 ])

## Part 9 — Broadcasting

In [ ]:
# Task 20: Add 5 to every mark

marks = np.array([60, 70, 80, 90])

# Write your code here

print(marks + 5)


[65 75 85 95]


In [ ]:
arr =[10,20,30.40]
arr2 =[]

for i in arr:
    print(i +5)

15
25
35.4


In [ ]:
# Task 21: Apply a 10% bonus to every mark
marks = np.array([60, 70, 80, 90])

# Hint: marks * 1.10
# Write your code here


## Part 10 — Matrix Operations

In [6]:
A = np.array([[1, 2 ], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Task 22: Find A+B, A-B, and A*B
# Write your code here
print(A+B)
print(A*B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [ ]:
# Task 23: Matrix multiplication
# Calculate A @ B
# Write your code here
print(A@B)

[[19 22]
 [43 50]]


## Part 11 — Mini ML Dataset

Columns: **Age | Study Hours | Marks**

In [ ]:
students = np.array([
    [20, 5, 80],
    [21, 6, 75],
    [22, 8, 90],
    [23, 4, 65],
    [24, 7, 85]
])

students


In [ ]:
# Task 24: Find the number of students
# Write your code here


In [9]:
number_of_students = data.shape[0]
print(number_of_students)

3


In [11]:
# Task 25: Find the average marks
# Write your code here
avg = np.mean(marks)
print(avg)

76.0


In [14]:
# Task 26: Extract the Study Hours column
# Write your code here
study_hours = data[:, 4]
print(study_hours)

IndexError: index 4 is out of bounds for axis 1 with size 3

In [ ]:
# Task 27: Find students who scored more than 80
# Write your code here
students_above_80 = data[data[:, 1] > 80]
print(students_above_80)

[]


In [ ]:

maximum_study_hours = np.max(data[:, 4])
print(maximum_study_hours)

IndexError: index 4 is out of bounds for axis 1 with size 3

In [26]:
# Task 29: Find the average of each column
# Write your code here
column_averages = np.mean(data, axis=0)
print(column_averages)


[40. 50. 60.]


In [27]:
# Task 30: Transpose the dataset
# Write your code here
transpose = data.T
print(transpose)


[[10 40 70]
 [20 50 80]
 [30 60 90]]


# Final Challenge

Solve without looking at previous examples:

1. Find number of students.
2. Find number of features.
3. Calculate average marks.
4. Find highest marks.
5. Find students with marks >= 80.
6. Calculate average study hours.
7. Find the student with highest study hours.
8. Add 5 bonus marks to every student.
9. Reshape the dataset into another valid shape, if possible.
10. Transpose the dataset.

In [ ]:
# Final Challenge

students = np.array([
    [20, 5, 80],
    [21, 6, 75],
    [22, 8, 90],
    [23, 4, 65],
    [24, 7, 85]
])

# Solve all 10 tasks here.

number_of_students = data.shape[0]
print("Number of students:", number_of_students)

number_of_features = data.shape[1]
print("Number of features:", number_of_features)

average_marks = np.mean(data[:, 1])
print("Average marks:", average_marks)

highest_marks = np.max(data[:, 1])
print("Highest marks:", highest_marks)

students_above_80 = data[data[:, 1] >= 80]
print("Students with marks >= 80:")
print(students_above_80)

average_study_hours = np.mean(data[:, 4])
print("Average study hours:", average_study_hours)

highest_study_hours = np.max(data[:, 4])
student_with_highest_study_hours = data[data[:, 4] == highest_study_hours]
print("Student with highest study hours:")
print(student_with_highest_study_hours)

bonus_data = data.copy()
bonus_data[:, 1] = bonus_data[:, 1] + 5
print("Dataset after adding 5 bonus marks:")
print(bonus_data)

reshaped_data = data.reshape(1, -1)
print("Reshaped dataset:")
print(reshaped_data)

transposed_data = data.T
print("Transposed dataset:")
print(transposed_data)

Number of students: 3
Number of features: 3
Average marks: 50.0
Highest marks: 80
Students with marks >= 80:
[[70 80 90]]


IndexError: index 4 is out of bounds for axis 1 with size 3